package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'MavenBuild2'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("MavenBuild2")) {
    check(artifactRules == "target/*.jar => artifacts") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = "target/plaindoll.jar => artifacts"
}
