package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'MavenBuild2'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("MavenBuild2")) {
    check(artifactRules == "target/*.jar => artifacts") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = "target/plaindoll.jar => artifacts"

    expectSteps {
        maven {
            name = "deploy"

            conditions {
                equals("teamcity.build.branch", "master")
            }
            goals = "clean deploy"
            pomLocation = "pom.xml"
        }
        maven {
            name = "test"
            id = "text"

            conditions {
                doesNotEqual("teamcity.build.branch", "master")
            }
            goals = "clean test"
            pomLocation = "pom.xml"
        }
    }
    steps {
        update<MavenBuildStep>(0) {
            clearConditions()

            conditions {
                equals("teamcity.build.branch", "refs/tags/master")
            }
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
        update<MavenBuildStep>(1) {
            clearConditions()

            conditions {
                doesNotEqual("teamcity.build.branch", "refs/tags/master")
            }
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
    }
}
