package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'GitHub'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("GitHub")) {
    val expected = GitVcsRoot({
        id("GitHub")
        name = "GitHub"
        url = "https://github.com/slateeho/TeamCityPipeline.git"
        branch = "refs/heads/master"
        checkoutSubmodules = GitVcsRoot.CheckoutSubmodules.IGNORE
        checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.NO_MIRRORS
        authMethod = password {
            userName = "slateeho"
            password = "credentialsJSON:54e33c7d-ffaa-4abc-a44d-eed4f6afda5e"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branch = "+:master"
    }

}
